-- Database: shop_services

-- DROP DATABASE IF EXISTS shop_services;

CREATE DATABASE shop_services
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Table: public.shop

-- DROP TABLE IF EXISTS public.shop;

CREATE TABLE IF NOT EXISTS public.shop
(
    shop_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    shop_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT shop_pkey PRIMARY KEY (shop_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.shop
    OWNER to postgres;

-- Table: public.product

-- DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_plu character varying(20) COLLATE pg_catalog."default" NOT NULL,
    product_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT product_pkey PRIMARY KEY (product_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.product
    OWNER to postgres;

-- Table: public.shop_order

-- DROP TABLE IF EXISTS public.shop_order;

CREATE TABLE IF NOT EXISTS public.shop_order
(
    order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    shop_id integer NOT NULL,
    order_date date NOT NULL,
    CONSTRAINT order_pkey PRIMARY KEY (order_id),
    CONSTRAINT shop_id_fk FOREIGN KEY (shop_id)
        REFERENCES public.shop (shop_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.shop_order
    OWNER to postgres;

-- Table: public.order_detail

-- DROP TABLE IF EXISTS public.order_detail;

CREATE TABLE IF NOT EXISTS public.order_detail
(
    order_detail_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_id integer NOT NULL,
    order_id integer NOT NULL,
    product_quantity integer NOT NULL,
    CONSTRAINT order_detail_pkey PRIMARY KEY (order_detail_id),
    CONSTRAINT order_id_fk FOREIGN KEY (order_id)
        REFERENCES public.shop_order (order_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT product_id_fk FOREIGN KEY (product_id)
        REFERENCES public.product (product_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.order_detail
    OWNER to postgres;

-- Table: public.remainder

-- DROP TABLE IF EXISTS public.remainder;

CREATE TABLE IF NOT EXISTS public.remainder
(
    remainder_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_id integer NOT NULL,
    shop_id integer NOT NULL,
    CONSTRAINT remainder_pkey PRIMARY KEY (remainder_id),
    CONSTRAINT product_id_fk FOREIGN KEY (product_id)
        REFERENCES public.product (product_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT shop_id_fk FOREIGN KEY (shop_id)
        REFERENCES public.shop (shop_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.remainder
    OWNER to postgres;

-- Table: public.action

-- DROP TABLE IF EXISTS public.action;

CREATE TABLE IF NOT EXISTS public.action
(
    action_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT action_pkey PRIMARY KEY (action_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.action
    OWNER to postgres;

-- Table: public.log_record

-- DROP TABLE IF EXISTS public.log_record;

CREATE TABLE IF NOT EXISTS public.log_record
(
    log_record_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_id integer NOT NULL,
    shop_id integer,
    product_plu character varying(20) COLLATE pg_catalog."default" NOT NULL,
    action_date date NOT NULL,
    CONSTRAINT log_record_pkey PRIMARY KEY (log_record_id),
    CONSTRAINT action_id_fk FOREIGN KEY (action_id)
        REFERENCES public.action (action_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.log_record
    OWNER to postgres;

